### __LEARNING OBJECTIVES AND LESSON OVERVIEW__

Red
__========================================================================__
#### __Learning Objectives__ 
-----
* In this lesson you will learn how to
  * Input matrices into Python
  * Explain functions you can use with Python

<br><br>

### __INTRODUCTION TO LINEAR ALGEBRA FUNCTIONS IN PYTHON__ 
__===========================================================================__

Orange
<br>
__==================================================================================__
#### __Introduction to Linear Algebra FUnctions in Python__ 
-----
* Bullet 1
* Bullet 2
  * Bullet 2a
  * Bullet 2b

In [1]:
import numpy as np
import random
# from numpy.linalg import multi_dot

In [19]:
# Given the follogin matrices and vectors:
M = np.linspace(-8, 8, 9).reshape(3, 3)
N = np.random.randint(-8, 8, size = (3, 3))
O = 2*N
v1 = np.array([1, 3, 5, 7])
v2 = np.array([2, 4, 6, 8])
v3 = np.array([-2, 5, 1, 3])

<br><br>

Yellow
__========================================================================__
#### __The dot() function does the product of either two matrices or two vectors__ 
-----
* Bullet 1
* Bullet 2
  * Bullet 2a
  * Bullet 2b

In [20]:
N.dot(M)

array([[ 32.,  36.,  40.],
       [-14., -12., -10.],
       [ 94.,  78.,  62.]])

In [21]:
v1.dot(v2)

100

<br><br>

Green
__========================================================================__
#### __The multidot() function returns the product of two or several matrices__ 
-----
* Bullet 1
* Bullet 2
  * Bullet 2a
  * Bullet 2b

In [22]:
np.linalg.multi_dot([M, N, O])

array([[-496.,   68.,  688.],
       [  20., -460.,  244.],
       [ 536., -988., -200.]])

<br><br>

Blue
__========================================================================__
#### __The vdot() function returns the product of two vectors. It does not perform a matrix multiplication. It should only be used for vectors__ 
-----
* Bullet 1
* Bullet 2
  * Bullet 2a
  * Bullet 2b

In [23]:
np.vdot(v1, v2)

100

<br><br>

Purple
__========================================================================__
#### __The inner() function returns the inner product of two arrays__ 
-----
* Bullet 1
* Bullet 2
  * Bullet 2a
  * Bullet 2b

In [24]:
np.inner(v3, v1)

39

<br><br>

Red
__========================================================================__
#### __The matmul() function returns the product of two matrices__ 
-----
* Bullet 1
* Bullet 2
  * Bullet 2a
  * Bullet 2b

In [25]:
np.matmul(M, N)

array([[ 84., -70.,  -4.],
       [ -6., -22.,   8.],
       [-96.,  26.,  20.]])

<br><br>

Orange
__========================================================================__
#### __The linalg.matrix_power(M, n) raises the square matrix M to the power of n__ 
-----
* Bullet 1
* Bullet 2
  * Bullet 2a
  * Bullet 2b

In [26]:
np.linalg.matrix_power(M, 3)

array([[-576., -432., -288.],
       [-144.,    0.,  144.],
       [ 288.,  432.,  576.]])

<br><br>

Yellow
__========================================================================__
#### __The linalg.eig(O) returns both the eigenvalues and eigenvectors of the matrix O__ 
-----
* Bullet 1
* Bullet 2
  * Bullet 2a
  * Bullet 2b

In [27]:
eig_vals, eig_vects = np.linalg.eig(O)

In [28]:
eig_vals

array([-4.18016421+8.33462154j, -4.18016421-8.33462154j,
       22.36032842+0.j        ])

In [29]:
eig_vects

array([[-0.40505142+0.421883j  , -0.40505142-0.421883j  ,
        -0.18739429+0.j        ],
       [-0.36982427-0.07672171j, -0.36982427+0.07672171j,
        -0.63083623+0.j        ],
       [-0.71783833+0.j        , -0.71783833-0.j        ,
         0.7529469 +0.j        ]])

<br><br>

Green
__========================================================================__
#### __The linalg(eigh(N) returns both the eigenvalues and the eigenvectors of a complex Hermitian matrix or a real symmetric matrix N__ 
-----
* Bullet 1
* Bullet 2
  * Bullet 2a
  * Bullet 2b

In [30]:
eigh_vals, eigh_vectors = np.linalg.eigh(N)

In [31]:
eigh_vals

array([-10.46547365,   5.34507714,  12.12039651])

In [32]:
eigh_vectors

array([[ 0.82849562, -0.48858049, -0.27364963],
       [ 0.23975171,  0.7510839 , -0.61513583],
       [ 0.50607719,  0.44402938,  0.73940773]])

<br><br>

Blue
__========================================================================__
#### __The linalg.det(N) returns the determinant of the matrix N__ 
-----
* Bullet 1
* Bullet 2
  * Bullet 2a
  * Bullet 2b

In [33]:
np.linalg.det(N)

242.99999999999994

-----
* The __linalg.inv(N)__ returns the inverse of the matrix N

In [34]:
np.linalg.inv(N)

array([[ 0.0617284 , -0.14403292, -0.12757202],
       [ 0.17283951, -0.06995885, -0.09053498],
       [ 0.27160494, -0.30041152, -0.09465021]])

<br><br>