#### __LEARNING OBJECTIVES__
-----

Red
<br>
__========================================================================__
##### __Learning Objectives__ 
-----
* In this lesson you will learn how to:
  * Input matrices in Python
  * Explain functions you can use in Python  

<br><br>

#### __INTRODUCTION TO LINEAR ALGEBRA FUNCTIONS IN PYTHON__
-----

Orange
<br>
__========================================================================__
##### __Introduction to Linear Algebra Function in Python__ 
-----
* Start by importing the libraries __numpy__ and __random__. 

  * We'll use these to build the following:
    * matrices _M, N,_ and _O_ 
    * vectors _v1, v2_, and _v3_
    <br><br>
  * Note that matrix _N_ will be composed of random integers within the specificed range and size


In [19]:
import numpy as np
# numpy.linalg import multi_dot
import random
import sympy as sy

In [20]:
# Given the following matrices and vectors
M = np.linspace(-8, 8, 9).reshape(3, 3)
N = np.random.randint(-8, 8, size = (3, 3))
O = 2*N
v1 = np.array([1, 3, 5, 7])
v2 = np.array([2, 4, 6, 8])
v3 = np.array([-2, 5, 1, 3])

-----
* Print each matrix and function. It'll be a bitch, but you'll need to enter them all in separate cells

In [21]:
M

array([[-8., -6., -4.],
       [-2.,  0.,  2.],
       [ 4.,  6.,  8.]])

In [22]:
N

array([[-7, -4,  4],
       [ 6,  0, -8],
       [ 7,  0, -1]])

In [23]:
O

array([[-14,  -8,   8],
       [ 12,   0, -16],
       [ 14,   0,  -2]])

In [24]:
v1

array([1, 3, 5, 7])

In [25]:
v2

array([2, 4, 6, 8])

In [26]:
v3

array([-2,  5,  1,  3])

Yellow
<br>
__========================================================================__
##### __The dot() function does the product of two matrices, or two vectors__ 
-----
* Don't confuse the __dot()__ function with the dot product or cross product from calculus. 
  * Matrix multiplication in linear algebra is its own beast, and that's what the __dot()__ function does.
  <br><br>
* Just like when we were printing our matrices and vectors, you'll notice that we have to do these all in separate cells. Each cell can apparently only produce one array at a time, and it will also default to the last array produced.
  <br><br>
* The code below shows the product of matrix N multiplied by matrix M.
  * Yes, it goes in that order. You'll learn later that order matters when multiplying  matrices.

In [27]:
N.dot(M)

array([[ 80.,  66.,  52.],
       [-80., -84., -88.],
       [-60., -48., -36.]])

In [28]:
v1.dot(v2)

100

-----
* Just to retierate that order matters, see how you get a completely different matrix and you go the other way around.
  <br><br>
* Wait why didn't the switched order affect the vector multiplication?
  * Both vectors only have 1 row, so that's less room to change things. The matrices above had 3 rows.

In [29]:
M.dot(N)

array([[ -8.,  32.,  20.],
       [ 28.,   8., -10.],
       [ 64., -16., -40.]])

In [30]:
v2.dot(v1)

100

Green
<br>
__========================================================================__
##### __The multi_dot() function returns the product or two several matrices__ 
-----
* The code below gives the product of the matrices _M, N_, and _O_

In [31]:
np.linalg.multi_dot([M, N, O])

array([[  776.,    64.,  -616.],
       [ -436.,  -224.,   116.],
       [-1648.,  -512.,   848.]])

Blue
<br>
__========================================================================__
##### __The vdot() function returns the product of two vectors. It does not perform matrix multiplication. It should only be used for vectors.__ 
-----
* Again, the __vdot()__ function only works with two vectors at a time. Can't do more than two, and can't do matrices.
  * Think of like a more specialized vector-specific __dot()__ function

In [32]:
np.vdot(v1, v2)

100

Purple
<br>
__========================================================================__
##### __The inner() function returns the inner product of two arrays__ 
-----
* Bullet 1
* Bullet 2
  * Bullet 2a
  * Bullet 2b

In [33]:
np.inner(v3, v1)

39

Red
<br>
__========================================================================__
##### __The matmul() function returns the product of two matrices__ 
-----
* __matmul()__ means matrix multiplication
* Bullet 2
  * Bullet 2a
  * Bullet 2b

In [34]:
np.matmul(M, N)

array([[ -8.,  32.,  20.],
       [ 28.,   8., -10.],
       [ 64., -16., -40.]])

Orange
<br>
__========================================================================__
##### __The linalg.matrix_power(M, n) raises the square matrix M to the power of n__ 
-----
* Bullet 1
* Bullet 2
  * Bullet 2a
  * Bullet 2b

In [41]:
np.linalg.matrix_power(M, 3)

array([[-576., -432., -288.],
       [-144.,    0.,  144.],
       [ 288.,  432.,  576.]])

Yellow
<br>
__========================================================================__
##### __The linalg.eig(O) returns both the eigenvalues and eigentvectors of the matrix O__ 
-----
* Bullet 1
* Bullet 2
  * Bullet 2a
  * Bullet 2b

In [43]:
eig_vals, eig_vects = np.linalg.eig(O)

In [44]:
eig_vals

array([-11.96500478+7.65531614j, -11.96500478-7.65531614j,
         7.93000956+0.j        ])

Green
<br>
__========================================================================__
##### __The linalgeigh(N) returns both the eigenvalues and eigenvectors of a complex Hermitian matrix or a real symmetric matrix N__ 
-----
* Bullet 1
* Bullet 2
  * Bullet 2a
  * Bullet 2b

In [45]:
eigh_vals, eigh_vectors = np.linalg.eigh(N)

In [46]:
eigh_vals

array([-13.55743852,  -0.44256148,   6.        ])

In [47]:
eigh_vectors

array([[-0.81470664,  0.05403484,  0.57735027],
       [ 0.36055777, -0.73257406,  0.57735027],
       [ 0.45414886,  0.67853922,  0.57735027]])

Blue
<br>
__========================================================================__
##### __The linalg.det(N) returns the determinant of the matrix N__ 
-----
* Bullet 1
* Bullet 2
  * Bullet 2a
  * Bullet 2b

In [48]:
np.linalg.det(N)

199.99999999999991

-----
* The __linalg.inv(N)__ returns the inverse of the matrix _N_

In [51]:
np.linalg.inv(N)

array([[-0.   , -0.02 ,  0.16 ],
       [-0.25 , -0.105, -0.16 ],
       [-0.   , -0.14 ,  0.12 ]])