#### __LEARNING OBJECTIVES__
-----

Red
<br>
__========================================================================__
##### __Learning Objectives__ 
-----
* In this lesson you will learn ohw to
  * Input matrices into Python using three different methods
  * Grab specific integers in matrices

<br><br>

#### __USING MATRICES IN PYTHON__
-----

Orange
<br>
__========================================================================__
##### __Importing Libraries__ 
-----
* Bullet 1
* Bullet 2
  * Bullet 2a
  * Bullet 2b

In [1]:
import numpy as np
import random

Yellow
<br>
__========================================================================__
##### __Building Matrices Using NumPy__ 
-----
* Bullet 1
* Bullet 2
  * Bullet 2a
  * Bullet 2b

In [2]:
L = np.linspace(0, 120, 25)
L

array([  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,
        55.,  60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100., 105.,
       110., 115., 120.])

In [3]:
M = L.reshape(5, 5)
M

array([[  0.,   5.,  10.,  15.,  20.],
       [ 25.,  30.,  35.,  40.,  45.],
       [ 50.,  55.,  60.,  65.,  70.],
       [ 75.,  80.,  85.,  90.,  95.],
       [100., 105., 110., 115., 120.]])

In [4]:
R = np.random.randint(-5, 4, size = (4, 4))
R

array([[-5,  0,  3, -4],
       [-4,  0, -3, -4],
       [ 0, -4, -2, -4],
       [ 1, -2,  2, -1]])

Green
<br>
__========================================================================__
##### __Selecting Specific Entry of a Matrix__ 
-----
* Bullet 1
* Bullet 2
  * Bullet 2a
  * Bullet 2b

In [5]:
# Index starts at 0, 1, 2, 3

In [6]:
M

array([[  0.,   5.,  10.,  15.,  20.],
       [ 25.,  30.,  35.,  40.,  45.],
       [ 50.,  55.,  60.,  65.,  70.],
       [ 75.,  80.,  85.,  90.,  95.],
       [100., 105., 110., 115., 120.]])

In [7]:
M[0]

array([ 0.,  5., 10., 15., 20.])

In [8]:
M[4]

array([100., 105., 110., 115., 120.])

In [9]:
M[-1]

array([100., 105., 110., 115., 120.])

In [10]:
M[:, 0]

array([  0.,  25.,  50.,  75., 100.])

In [11]:
M[0:5, 0]

array([  0.,  25.,  50.,  75., 100.])

In [12]:
M[0:3, 1:4]

array([[ 5., 10., 15.],
       [30., 35., 40.],
       [55., 60., 65.]])

<br><br>