#### __LEARNING OBJECTIVES__
-----

Red
<br>
__========================================================================__
##### __Learning Objectives__ 
-----
* In this lesson you will learn how to
  * Input matrices into Python using three different methods
  * Grab specific integers in matrices

<br><br>

#### __USING MATRICES IN PYTHON__
-----

Orange
<br>
__========================================================================__
##### __Importing Libraries__ 
-----
* Start by importing the library __numpy__ and __random__
* We actually won't be using __sympy__ this time around beacuse these are some long ass arrays
  
  

In [30]:
import numpy as np
import random

Yellow
<br>
__========================================================================__
##### __Building Matrices Using NumPy__ 
-----
* The code below creates an array matrix <span style = font-family:times>_L_</span> with. numbers starting from 0 to 120. This whole array will be divided into 25 entries. 
  

In [31]:
L = np.linspace(0, 120, 25)
L

array([  0.,   5.,  10.,  15.,  20.,  25.,  30.,  35.,  40.,  45.,  50.,
        55.,  60.,  65.,  70.,  75.,  80.,  85.,  90.,  95., 100., 105.,
       110., 115., 120.])

-----
* If we printed this with sympy, we'd see that this would be one long ass column vector with 25 rows.

  * To make this into an easier-to-read matrix, we're going to reshape it into a matrix style array with 5 rows and 5 columns.

In [32]:
M = L.reshape(5, 5)
M

array([[  0.,   5.,  10.,  15.,  20.],
       [ 25.,  30.,  35.,  40.,  45.],
       [ 50.,  55.,  60.,  65.,  70.],
       [ 75.,  80.,  85.,  90.,  95.],
       [100., 105., 110., 115., 120.]])

-----
* We're going to directly create a matrix <span style = font-family:times>_R_</span> made up of random integers (no floating points) from -5 to 4. We also want the matrix have 4 rows and 4 columns.

In [33]:
R = np.random.randint(-5, 4, size = (4, 4))
R

array([[-2, -1,  2, -5],
       [-2, -5, -5,  0],
       [ 3, -2, -4,  0],
       [-3,  1,  0, -4]])

Green
<br>
__========================================================================__
##### __Selecting Specific Entry of a Matrix__ 
-----
* The codes below allow you to select a specific entry within a given matrix.
  * The index goes from 0, 1, 2, 3...
  <br><br>
  -----
* Let's start printing out the matrix <span style = font-family:time>_M_</span>

In [35]:
M

array([[  0.,   5.,  10.,  15.,  20.],
       [ 25.,  30.,  35.,  40.,  45.],
       [ 50.,  55.,  60.,  65.,  70.],
       [ 75.,  80.,  85.,  90.,  95.],
       [100., 105., 110., 115., 120.]])

  -----
* This code prints the first row.
  * Remember that 0 is the first number of our index because Python


In [36]:
M[0]

array([ 0.,  5., 10., 15., 20.])

  -----
* This code prints the fifth row
  * Remember that 4 is the fifth number of our index

In [45]:
M[4]

array([100., 105., 110., 115., 120.])

  -----
* This code also prints the fifth row. 
  * It's actually just printing the last row, so if we had 6 rows, it would print the sixth one.

In [47]:
M[-1]

array([100., 105., 110., 115., 120.])

  -----
* To pull up the first column, use the code below
  * Since rows are always the first parameter, we us __:__ to indicate that we still want to return all the row values. We put in a comma to indicate that we want columns, since that's the second parameter.

In [39]:
M[:, 0]

array([  0.,  25.,  50.,  75., 100.])

  -----
* Instead of using __:__ as a wild card call for all row values, we can limit to a specific range.
  * The code below pulls up all the row values from rows 0-5 for the first column

In [40]:
M[0:5, 0]

array([  0.,  25.,  50.,  75., 100.])

  -----
* The code below pulls up all the row values for rows 0-3 in columns 1-4.

In [41]:
M[0:3, 1:4]

array([[ 5., 10., 15.],
       [30., 35., 40.],
       [55., 60., 65.]])

<br><br>