#### __LEARNING OBJECTIVES__
-----

Red
<br>
__========================================================================__
##### __Learning Objectives__ 
-----
* In this lesson you will learn how to
  * Solve linear aequations using Python
  
  

Orange
<br>
__========================================================================__
##### __Lesson Oveiew__ 
-----
* Solve linear equations using the inverse method
* Solve linear equations using reduced row echelon form
* Solve linear equation using the __la.solve()__ method

<br><br>

#### __SOLVING LINEAR EQUATIONS USING PYTHON__
-----

Yellow
<br>
__========================================================================__
##### __Importing libraries__ 
-----
* Bullet 1
* Bullet 2
  * Bullet 2a
  * Bullet 2b

In [25]:
import numpy as np
from IPython.display import display, Latex
import sympy as sy

Given the folowing system of linear equations (<span style = 'font-family:times'>***I***</span>):
  
  <span style = 'font-family:times'>
  4x + 3y + 2z = 25 <br>
  -2x + 2y + 3z = -10<br>
  3x - 5y + 2z = -4
  </span>

Green
<br>
__========================================================================__
##### __Solve Linear Equation Using Inverse Method__ 
-----
* Bullet 1
* Bullet 2
  * Bullet 2a
  * Bullet 2b

In [26]:
# Let M be the coeffiient matrix:
M = np.array([[4, 3, 2], [-2, 2, 3], [3, -5, 2]])
M

array([[ 4,  3,  2],
       [-2,  2,  3],
       [ 3, -5,  2]])

In [27]:
# Let K be the column matrix:
K = np.array([[25], [-10], [-4]])
K

array([[ 25],
       [-10],
       [ -4]])

In [28]:
# Let V be the following matrix:
V = np.array([['x'], ['y'], ['z']])
V

array([['x'],
       ['y'],
       ['z']], dtype='<U1')

Blue
<br>
__========================================================================__
##### __Equation (<span style = 'font-family:times'>*I*</span>) can be written as...__ 
-----
* Equation (<span style = 'font-family:times'>***I***</span>) can be written as...
    * <span style = 'font-family:times'>_M_ * _V_ = _K_</span>
    <br>

    so...
<br>

* <span style = 'font-family:times'>___V_</span> = Inverse of <span style = 'font-family:times'>_M_</span> times <span style = 'font-family:times'>_K___</span>
  * <span style = 'font-family:times'>_V_</span> = <span style = 'font-family:times'>_M_<sup> -1</sup> * <span style = 'font-family:times'>_K_ 

Purple
<br>
__========================================================================__
##### __Solve Linear Equation Using Inverse Method__ 
-----
* Bullet 1
* Bullet 2
  * Bullet 2a
  * Bullet 2b

In [30]:
V = np.linalg.inv(M).dot(K)
V

array([[ 5.],
       [ 3.],
       [-2.]])

* This shows that:
<span style = 'font-family:times'>
  * _x_ = 5
  * _y_ = 3
  * _z_ = -2
</span>

<br><br>

Red
<br>
__========================================================================__
##### __Solve Linear Equation Using Redued Row Echelon Form__ 
-----
* Bullet 1
* Bullet 2
  * Bullet 2a
  * Bullet 2b

In [37]:
# The augmented matrix A is:
A = sy.Matrix([[4, 3, 2, 25], [-2, 2, 3, -10], [3, -5, 2, -4]])
A

Matrix([
[ 4,  3, 2,  25],
[-2,  2, 3, -10],
[ 3, -5, 2,  -4]])

In [40]:
M_sy = sy.Matrix(M)
M_sy

Matrix([
[ 4,  3, 2],
[-2,  2, 3],
[ 3, -5, 2]])

In [41]:
K_sy = sy.Matrix(K)
K_sy

Matrix([
[ 25],
[-10],
[ -4]])

In [42]:
sy.Matrix([[4, 3, 2, 25], [-2, 2, 3, -10], [3, -5, 2, -4]]).rref(pivots = False)

Matrix([
[1, 0, 0,  5],
[0, 1, 0,  3],
[0, 0, 1, -2]])

* This shows that...
<span style = 'font-family:times'>
  * _x_ = 5
  * _y_ = 3
  * _z_ = -2
</span>

Orange
<br>
__========================================================================__
##### __Solve Linear Equation Using la.solve() method__ 
-----
* Bullet 1
* Bullet 2
  * Bullet 2a
  * Bullet 2b

In [44]:
Sol = np.linalg.solve(M, K)
Sol

array([[ 5.],
       [ 3.],
       [-2.]])

<br><br>