#### __Introduction to Matrices in Python Using Numpy__ 

* Always begin by importing __numpy__
* We'll also be importing __random__ to randomize the entries within several of our matrices

In [1]:
import numpy as np
import random

* The matrix __M__ below isn't randomized and instead has 3 rows and 3 columns containing the numbers from 1 to 9. 

In [12]:
M = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
M

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

---------------------------------------------------------

* __Two-by-two matrix__
  * The matrtix __T__ below is an example of a matrix with 2 rows and 2 columns
  * The entries in the matrix __T__ will be any numbers from -2 to 3

In [13]:
T = np.random.randint(-2, 3, size = (2, 2))
T

array([[ 0, -2],
       [ 1,  2]])

<br><br>

#### __Particular__ __Matrices__

* __Identity Matrix__
    * I is an example of an identity matrix with 3 rows and 4 columns
    * Notice how the fourth column of I only has an entries of 0's. However, a fourth row on the fourth column  in I2 would have an entry of 1.

In [14]:
I = np.eye(3, 4)
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [15]:
I2 = np.eye(4, 4)
I2

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

---------------------------------------------------------

* __Zeroes Matrix__
    * Below is a zeroes matrix with 3 rows and 3 columns
    * Note that to run this code, enter the size as a tuple within the function

In [16]:
Z = np.zeros((3, 3))
Z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

---------------------------------------------------------

* __Ones Matrix__

    * Below is a ones matrix with 5 rows and 4 columns
    * Note that to run this code, enter the size as a tuple within the function

In [17]:
O = np.ones((5, 4))
O

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

---------------------------------------------------------

* __Diagonal Matrix__

    * The matrix __D__ below is a diagonal matrix where the entries 1, 2, 3 form the middle diagonal of the matrix starting from row 1, column 1
    * The matrix __C__ below takes the entries that would form the diagonal matrix from __M__ at the beginning of the notebook page and puts those entries in a matrix __C__ made up of 1 row and 1 column

In [18]:
D = np.diag([1, 2, 3])
D

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [19]:
C = np.diag(M)
C

array([1, 5, 9])

<br><br>